declare module 'react-native-ico-universalicons' {
    import { ReactNode } from 'react';
    import { SvgProps, AdditionalProps } from 'react-native-svg';

    type iconNames = 'angry-face-of-square-shape-and-straight-lines' |
      'angry-face-of-square-shape-outline' |
      'angry-face' |
      'arrow-pointing-to-left' |
      'arrow-turning-to-right' |
      'arrows-circle' |
      'audio-headset-tool' |
      'bad-face' |
      'bars-graphic-1' |
      'bars-graphic' |
      'bars-symbol' |
      'basket-black-shape' |
      'battery-almost-full' |
      'battery-status-sign-with-less-than-half-energy-charge' |
      'birds-home' |
      'bishop-chess-piece' |
      'black-folder-shape-for-interface' |
      'black-golf-ball' |
      'black-hand-pointing-to-right' |
      'black-hand-pointing-up' |
      'black-heart-love-symbol' |
      'black-label-in-horizontal-position' |
      'black-male-user-symbol' |
      'black-open-envelope-back' |
      'black-placeholder-variant' |
      'black-suitcase' |
      'black-triangular-arrowhead-pointing-to-left-direction' |
      'blind-face' |
      'blind-square-face' |
      'boring-face' |
      'brush-tool' |
      'bubbles-interface-symbol-for-talk' |
      'buildings' |
      'calculator' |
      'calendar-page-symbol-on-day-15' |
      'calling-out-symbol-of-auricular-with-arrow' |
      'camera-to-take-photos' |
      'centered-paragraph-text-lines-symbol-for-interface' |
      'check-document-interface-square-symbol' |
      'check-mark-in-a-circle' |
      'check-sign' |
      'checked-page-symbol' |
      'circle-of-arrows-couple' |
      'circular-clock-symbol-for-interface' |
      'clock-circular-tool-shape' |
      'close-hanging-signal-for-commerce' |
      'cloud-black-shape-with-a-cross' |
      'cloud-black-shape-with-three-dots-inside' |
      'cloud-lock' |
      'cloud-with-check-sign' |
      'cloud-with-minus-sign' |
      'clover-black-shape' |
      'cogs-on-wheels-interface-symbol-for-settings-edition-button' |
      'cogwheel' |
      'coins-stack' |
      'color-palette-for-painter' |
      'creative-lightbulb-symbol-black-shape' |
      'credit-card-tool' |
      'cross-delete-or-close-circular-button-interface-symbol' |
      'cross-gross-symbol' |
      'cross-in-a-circle' |
      'dark-cloud-shape' |
      'diamond-symbol' |
      'dice-with-five-dots' |
      'disc-outline-of-gross-line' |
      'discs' |
      'doctor-suitcase-with-a-cross' |
      'document-lock-interface-security-symbol' |
      'document-lock-symbol' |
      'document-rounded-square-interface-symbol-with-text-lines' |
      'document-with-minus-sign' |
      'documents-check-interface-symbol-of-text-lines-in-rounded-square' |
      'documents-plus-symbol-for-interface-with-rounded-square-shape' |
      'documents-rounded-square-symbol' |
      'dollar-coin-symbol' |
      'dollar-coin' |
      'dollar-sign' |
      'down-arrow-1' |
      'down-arrow-in-a-circle' |
      'down-arrow' |
      'down-arrowhead-in-a-circle' |
      'down-arrows' |
      'down-double-arrow' |
      'download-symbol' |
      'emoticon-in-love-of-square-face-shape' |
      'empty-battery-interface-status-symbol' |
      'empty-glass-outline' |
      'equalizer' |
      'euro-coin' |
      'euro-sign-in-a-circle' |
      'euro' |
      'exclamation-sign-warning-interface-symbol' |
      'eye-shape-variant-interface-view-symbol' |
      'eyedropper-black-tool-silhouette' |
      'eyeglass-of-rectangular-shape' |
      'eyeglasses-of-circular-shape' |
      'face-of-silence-with-a-cross-as-mouth' |
      'facebook-logo-in-circular-shape' |
      'facebook-logo' |
      'female-symbol' |
      'floating-tool-to-save-lives' |
      'folder-check-symbol' |
      'folder-with-minus-sign-interface-symbol' |
      'folder-with-plus-sign-for-interface-button-to-add' |
      'four-arrows-interface-symbol-to-maximize-size' |
      'four-arrows-pointing-center-interface-symbol-to-minimize' |
      'free-tag-for-commerce' |
      'frown-face' |
      'glass-full-of-liquid' |
      'glass' |
      'global-interface-symbol-of-earth-grid' |
      'graphic-page-symbol' |
      'graphic-page' |
      'hand-pointing-down' |
      'hand-pointing-to-left-direction' |
      'hand-watch' |
      'happy-face' |
      'hd' |
      'heart-black-shape-symbol' |
      'hearts' |
      'hierarchical-network' |
      'home-black-shape' |
      'home-black-silhouette' |
      'home-building-symbol-variant' |
      'home-interface-symbol-with-a-window-of-squares' |
      'home-sign' |
      'home' |
      'horse-black-chess-piece-shape-from-side-view' |
      'hot-drink-mug' |
      'house-black-shape-for-home-interface-symbol' |
      'house' |
      'id-card-interface-symbol' |
      'image-interface-symbol-with-a-landscape' |
      'images-interface-symbol' |
      'incoming-call-interface-symbol-with-telephone-auricular-and-left-arrow-pointing-to-it' |
      'increase-volume-speaker-interface-symbol' |
      'info-circular-interface-symbol' |
      'information-interface-letter-symbol' |
      'iphone' |
      'joystick-games-control-tool' |
      'jpg-picture-square-symbol-for-interface' |
      'key-in-vertical-position-for-interface-security-symbol' |
      'king-chess-piece-shape' |
      'label-black-shape-rotated-to-left' |
      'label' |
      'laptop' |
      'left-arrow-symbol-in-a-circle' |
      'left-arrowhead-in-a-circle' |
      'left-arrowhead' |
      'left-arrowheads-couple' |
      'left-arrowheads-triangles' |
      'left-arrows' |
      'letter-type-interface-symbol' |
      'lifeline-signal' |
      'link-interface-symbol' |
      'list-interface-symbol' |
      'lock-a-folder-interface-symbol' |
      'lock-page-interface-symbol' |
      'lock-rectangular-padlock-shape' |
      'locked-open-folder-interface-symbol' |
      'magnifying-glass-on-bars-graphic' |
      'magnifying-glass-with-minus-sign' |
      'magnifying-glass' |
      'male-symbol' |
      'males-group' |
      'man-shape' |
      'map-folded-paper' |
      'marketing-viral' |
      'maximal-volume-audio-interface-symbol-of-a-speaker-side-view-with-lines-representing-sound' |
      'minus-pages-sign' |
      'minus-sign-in-a-circle' |
      'minus-sign-of-horizontal-bar' |
      'money-eyes-on-square-face' |
      'money-face' |
      'monitor-tool-symbol' |
      'monitor-with-stats-graphic' |
      'monthly-calendar' |
      'movie-camera-interface-symbol-with-play-triangle' |
      'movie-camera-silhouette' |
      'movie-camera' |
      'movie-film-reel' |
      'movie-interface-symbol' |
      'movie-photogram' |
      'movie-square-sign' |
      'music-note' |
      'music-square-symbol' |
      'musical-note-symbol-1' |
      'musical-note-symbol' |
      'musical-note-with-song-name-lines' |
      'musical-notes-sign' |
      'mute-interface-audio-symbol-of-a-speaker-with-a-cross' |
      'navigate-to-end-right-arrow-symbol-with-vertical-bar' |
      'navigate-to-start-letter-k-sign' |
      'network-connection' |
      'new-tag' |
      'news-interface-symbol' |
      'no-water-symbol-od-a-drop-with-a-slash' |
      'open-black-folder-interface-symbol' |
      'open-folder-with-minus-sign' |
      'open-folder-with-plus-sign' |
      'open-folder-with-verification-sign' |
      'open-hanging-signal' |
      'opened-back-envelope-with-down-arrow' |
      'opened-envelope-back-with-up-arrow' |
      'oval-black-speech-bubble' |
      'page-code-symbol' |
      'page-interface-symbol' |
      'page-symbol-1' |
      'page-symbol' |
      'pages-interface-symbol-of-black-squares' |
      'paint-roller-silhouette' |
      'paragraph-justified-option-symbol-for-interface-of-five-parallel-horizontal-lines' |
      'paragraph-left-alignment-interface-symbol' |
      'paragraph-left-alignment-symbol-for-interface' |
      'pause-symbol' |
      'pawn-black-silhouette' |
      'peace-symbol' |
      'pen-feather-black-diagonal-shape-of-a-bird-wing' |
      'pen-point' |
      'pen-tool-on-diagonal-position' |
      'pencil-in-diagonal-position-black-symbol-for-interface' |
      'pencil-on-a-square-outline' |
      'pencil-tool-symbol-in-diagonal-position-for-interface' |
      'pencil-write-interface-symbol' |
      'percentage-symbol' |
      'phone-auricular-symbol' |
      'phone-cabin-or-small-building-and-a-trash-can' |
      'phone-digital-communication-tool' |
      'photo-camera-interface-symbol-for-button' |
      'piano-square-symbol' |
      'pie-graphic-symbol-for-business-stats' |
      'pie-graphic' |
      'placeholders' |
      'planet-earth-1' |
      'planet-earth-grid-symbol' |
      'planet-earth' |
      'plug' |
      'plus-page-interface-add-symbol' |
      'plus-sign-in-a-dark-cloud-internet-symbol' |
      'plus-sign' |
      'plus-zoom-magnifying-glass-interface-symbol' |
      'pound-coin' |
      'power' |
      'queen-chess-piece-black-shape' |
      'redo-arrow-symbol' |
      'rent-hanging-signal' |
      'retro-photo-camera-symbol-of-square-shape' |
      'right-arrow-in-a-circle' |
      'right-arrow' |
      'right-arrowhead-black-triangular-shape' |
      'right-arrowhead-in-a-circle' |
      'right-arrowhead' |
      'right-arrowheads-1' |
      'right-arrowheads' |
      'right-arrows' |
      'right-triangular-arrowhead' |
      'sad-emoticon-square-face' |
      'sad-face-variant' |
      'sad-face' |
      'sale' |
      'sd-card-rectangular-shape' |
      'shield-black-shape' |
      'shock-face-of-square-shape-with-opened-oval-mouth' |
      'shock-face-of-square-shape' |
      'shocked-face-of-square-shape' |
      'shopping-trolley' |
      'shuffle-arrows-symbol-for-interface' |
      'silent-face-with-a-cross-mouth-shape' |
      'smile-face-of-square-shape-with-closed-happy-eyes' |
      'smile-face-with-sunglasses' |
      'smile-face' |
      'smile-square-face' |
      'smiley-in-love' |
      'smiley-square-face-with-sunglasses' |
      'spade-symbol' |
      'speaker-audio-tool-symbol' |
      'speedometer-circular-tool-symbol-for-speed-control-on-vehicles' |
      'square-of-rounded-corners' |
      'square-with-verification-sign' |
      'star-black-fivepointed-shape' |
      'star-tag-black-shape' |
      'stats-down' |
      'stats-graphic-1' |
      'stats-graphic' |
      'stats-up-graphic' |
      'stats' |
      'sterling-pound-sign-of-money' |
      'sterling-pounds-coin' |
      'stethoscope-medical-tool' |
      'straight-face' |
      'suitcases' |
      'sun-shape' |
      'surprised-face' |
      'tablet-tool' |
      'tag-black-shape' |
      'tags-shapes' |
      'talk-bubble-with-plus-sign' |
      'talk-face-smiley' |
      'talk-oval-bubble-with-minus-sign' |
      'text-document-add-button-with-plus-sign' |
      'text-document-square-rounded-shape-with-minus-sign' |
      'tower-black-chess-piece-shape' |
      'trash-black-shape' |
      'trash-can-with-cover-from-side-view' |
      'turn-left-arrow-symbol' |
      'tv-monitor-tool' |
      'two-movie-frames' |
      'undo-circular-arrow' |
      'university-graduates-cap-silhouette' |
      'unlock-padlock-interface-silhouette-symbol' |
      'unlock-page-symbol' |
      'up-arrow-1' |
      'up-arrow-symbol-in-a-circle' |
      'up-arrow' |
      'up-arrowhead-in-a-circle' |
      'up-arrowheads' |
      'up-arrows' |
      'upload' |
      'usb-tool' |
      'user-check-interface-symbol' |
      'user-male-black-shape-with-plus-sign' |
      'user-symbol' |
      'user-with-cross-sign' |
      'user-with-minus-sign-1' |
      'user-with-minus-sign' |
      'user-with-plus-sign' |
      'users-sign' |
      'usher-1' |
      'usher-2' |
      'usher-man-with-tie' |
      'usher-shape' |
      'usher' |
      'video-camera-black-silhouette-symbol' |
      'warning-exclamation-sign-in-a-circle' |
      'warning-page-symbol' |
      'water-drop-black-shape' |
      'water-drop-shape-outline' |
      'web-square-and-lines-symbol' |
      'wifi-interface-symbol' |
      'window-of-four-rounded-squares' |
      'wink-circular-face-symbol' |
      'winking-smiling-face' |
      'yen-sign';

    type backgroundType = 'circle' | 'rect' | 'button';

    type positionType = 'top' | 'bottom' | 'right' | 'left' |
      'top_right' | 'top_left' | 'bottom_right' | 'bottom_left';

    type backgroundTypeObj = {
      type?: backgroundType;
      color?: string;
      radius?: number;
      borderRadius?: number;
    };

    type badgeTypeObj = {
      value?: number | string;
      fontSize?: string;
      position?: positionType;
      color?: string;
      backgroundColor?: string;
      radius?: number;
    };

    interface IconProps {
      name: iconNames;
      width?: number;
      height?: number;
      color?: string;
      stroke?: number;
      background?: backgroundType | backgroundTypeObj;
      badge?: number | string | badgeTypeObj;
    }

    const Icon: (props: IconProps & SvgProps & AdditionalProps) => ReactNode;

    export { iconNames };
    export default Icon;
}
